import { PLATFORM_ENDPOINTS } from "./platform-endpoints";

export const PLATFORM_API_CONTRACT = [
  {
    group: "Platform",
    method: "GET",
    path: PLATFORM_ENDPOINTS.company,
    description: "Returns the active company workspace.",
    usedBy: ["/dashboard", "/dashboard/admin"],
  },
  {
    group: "Platform",
    method: "GET",
    path: PLATFORM_ENDPOINTS.modules,
    description: "Returns enabled or purchased modules for the company.",
    usedBy: ["/dashboard", "/dashboard/admin"],
  },
  {
    group: "Platform",
    method: "GET",
    path: PLATFORM_ENDPOINTS.users,
    description: "Returns company users, roles, and allowed modules.",
    usedBy: ["/dashboard/admin"],
  },
  {
    group: "Platform",
    method: "GET",
    path: PLATFORM_ENDPOINTS.alerts,
    description: "Returns platform alerts across modules.",
    usedBy: ["/dashboard"],
  },
  {
    group: "Platform",
    method: "GET",
    path: PLATFORM_ENDPOINTS.recentActivity,
    description: "Returns recent company activity timeline items.",
    usedBy: ["/dashboard"],
  },
  {
    group: "Fleet",
    method: "GET",
    path: PLATFORM_ENDPOINTS.fleetStats,
    description: "Returns fleet dashboard totals.",
    usedBy: ["/dashboard/fleet"],
  },
  {
    group: "Fleet",
    method: "GET",
    path: PLATFORM_ENDPOINTS.trucks,
    description: "Returns active trucks and latest truck status.",
    usedBy: ["/dashboard", "/dashboard/fleet"],
  },
  {
    group: "Fleet",
    method: "GET",
    path: PLATFORM_ENDPOINTS.drivers,
    description: "Returns drivers, active status, and assigned trucks.",
    usedBy: ["/dashboard/admin"],
  },
  {
    group: "Fleet",
    method: "GET",
    path: PLATFORM_ENDPOINTS.devices,
    description: "Returns Android tablet/device assignments and last seen data.",
    usedBy: ["/dashboard/admin"],
  },
  {
    group: "eTickets",
    method: "GET",
    path: PLATFORM_ENDPOINTS.etickets,
    description: "Returns all visible eTickets for the company.",
    usedBy: ["/dashboard", "/dashboard/etickets"],
  },
  {
    group: "eTickets",
    method: "GET",
    path: "/api/etickets/:token",
    description: "Returns one public eTicket by token.",
    usedBy: ["/eticket/[token]"],
  },
  {
    group: "Dispatch",
    method: "GET",
    path: PLATFORM_ENDPOINTS.dispatchStats,
    description: "Returns dispatch dashboard totals.",
    usedBy: ["/dashboard/dispatch"],
  },
  {
    group: "Dispatch",
    method: "GET",
    path: PLATFORM_ENDPOINTS.dispatchLoads,
    description: "Returns today’s dispatch loads.",
    usedBy: ["/dashboard/dispatch"],
  },
  {
    group: "Reports",
    method: "GET",
    path: PLATFORM_ENDPOINTS.reportStats,
    description: "Returns report dashboard totals.",
    usedBy: ["/dashboard/reports"],
  },
  {
    group: "Reports",
    method: "GET",
    path: PLATFORM_ENDPOINTS.reports,
    description: "Returns available generated reports.",
    usedBy: ["/dashboard/reports"],
  },
  {
    group: "AI",
    method: "GET",
    path: PLATFORM_ENDPOINTS.aiInsights,
    description: "Returns AI-generated operational insights.",
    usedBy: ["/dashboard", "/dashboard/ai"],
  },
] as const;