import type { Metadata } from "next";
import ContactForm from "../components/ContactForm";
import Footer from "../components/Footer";
import { Icon } from "../components/Icons";
import Navbar from "../components/Navbar";
import PageHero from "../components/PageHero";

export const metadata: Metadata = { title: "Start a Project", description: "Tell AtlasBlake Technologies about your website, custom software, mobile application, automation, integration, or existing-system project.", alternates: { canonical: "/contact" } };
export default function ContactPage(){return <main><Navbar/><PageHero eyebrow="Start a project" title="Tell us what you want to build." text="Need a new website, custom software, a mobile application, or a way to automate an existing process? Share what your business is trying to accomplish."/>
<section className="bg-[#f6f9fd] px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#1265df]">Contact information</p><h2 className="mt-5 text-4xl font-extrabold tracking-[-.04em]">Start the conversation.</h2><p className="mt-5 leading-7 text-[#607991]">A perfect technical specification is not required. Describe the business problem, the people involved, and what a better process would look like.</p><div className="mt-9 space-y-4"><ContactCard icon="mail" title="Project inquiries" value="contact@atlasblaketech.com" href="mailto:contact@atlasblaketech.com"/><ContactCard icon="mail" title="Existing-client support" value="support@atlasblaketech.com" href="mailto:support@atlasblaketech.com"/><ContactCard icon="map" title="Location" value="Dallas–Fort Worth, Texas"/><ContactCard icon="clock" title="Response" value="Project inquiries are reviewed as soon as possible."/></div></div><ContactForm/></div></section><Footer/></main>}
function ContactCard({icon,title,value,href}:{icon:"mail"|"map"|"clock";title:string;value:string;href?:string}){const content=<><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#eaf3ff] text-[#1265df]"><Icon name={icon} className="h-5 w-5"/></span><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#7890a7]">{title}</p><p className="mt-1 font-bold text-[#29455f]">{value}</p></div></>;return href?<a href={href} className="flex gap-4 rounded-2xl border border-[#dce7f2] bg-white p-5 transition hover:border-[#a8c8eb]">{content}</a>:<div className="flex gap-4 rounded-2xl border border-[#dce7f2] bg-white p-5">{content}</div>}
