import type { Metadata } from "next";
import Footer from "../components/Footer";
import { Icon } from "../components/Icons";
import MarketingCta from "../components/MarketingCta";
import Navbar from "../components/Navbar";
import PageHero from "../components/PageHero";
import SectionHeading from "../components/SectionHeading";

export const metadata: Metadata = { title: "About", description: "Learn why AtlasBlake Technologies builds practical websites, software, mobile applications, portals, integrations, and automation around real business problems.", alternates: { canonical: "/about" } };
export default function AboutPage(){return <main><Navbar/><PageHero eyebrow="About AtlasBlake" title="Built from solving real business problems." text="AtlasBlake Technologies exists to make useful custom technology more accessible to companies that need more than a generic template or an off-the-shelf subscription." primaryLabel="Start a Project" secondaryLabel="View Our Work" secondaryHref="/work"/>
<section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[.9fr_1.1fr]"><SectionHeading eyebrow="Our story" title="A software company shaped by the work itself."/><div className="space-y-6 text-lg leading-8 text-[#58728c]"><p>AtlasBlake began with a straightforward idea: businesses should not have to struggle with disconnected systems, repetitive processes, and software that does not match the way they actually work.</p><p>What started with website development grew into custom dashboards, mobile applications, digital ticketing, customer portals, operational integrations, and complete business platforms.</p><p>Today, AtlasBlake develops practical technology by first understanding the operation, the people using the system, and the result the business needs to achieve.</p></div></div></section>
<section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24 md:py-32"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="What guides the work" title="Practical technology. Honest progress. Long-term thinking." text="The best software is not the one with the longest feature list. It is the one people can use confidently to get meaningful work done."/><div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[["users","Start with the user","Understand the person doing the work before deciding what the interface should do."],["layers","Build in useful stages","Launch the highest-value workflow first instead of waiting for an oversized perfect system."],["shield","Be clear and dependable","Protect business data, communicate honestly, and avoid promising outcomes the system cannot support."],["chart","Design for growth","Create foundations that can support new users, workflows, integrations, and products over time."]].map(([icon,title,text])=><div key={title} className="marketing-card p-7"><Icon name={icon as "users"} className="h-7 w-7 text-[#1265df]"/><h2 className="mt-5 text-xl font-extrabold">{title}</h2><p className="mt-4 leading-7 text-[#607991]">{text}</p></div>)}</div></div></section>
<section className="bg-[#06172d] px-6 py-24 text-white"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.24em] text-blue-300">Based in DFW</p><h2 className="mt-5 text-4xl font-extrabold tracking-[-.045em] md:text-6xl">Local understanding. Cloud-scale possibilities.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">AtlasBlake Technologies is based in the Dallas–Fort Worth area and builds for businesses whose work happens in offices, trucks, jobsites, shops, and customer homes—not only behind a desk.</p></div><div className="rounded-[28px] border border-white/10 bg-white/[.05] p-8"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-500/20 text-blue-300"><Icon name="map" className="h-6 w-6"/></span><div><p className="font-extrabold">Dallas–Fort Worth, Texas</p><p className="mt-2 leading-7 text-slate-300">Serving companies locally and building cloud systems that can be used anywhere.</p></div></div></div></div></section><MarketingCta/><Footer/></main>}
