import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Footer from "../../components/Footer";
import { Icon } from "../../components/Icons";
import MarketingCta from "../../components/MarketingCta";
import Navbar from "../../components/Navbar";
import WebsiteShowcase from "../../components/WebsiteShowcase";

export const metadata: Metadata = {
  title: "NexDrain Plumbing Website Case Study",
  description: "See how AtlasBlake Technologies created a professional, mobile-first website and local SEO foundation for NexDrain Plumbing in Dallas–Fort Worth.",
  alternates: { canonical: "/work/nexdrain-plumbing" },
};

const built = ["Complete website redesign", "Mobile-first customer experience", "Individual plumbing service pages", "Local service-area content", "Before-and-after project galleries", "Customer review integration", "Call, text, and request-service pathways", "Google Analytics and Search Console foundation", "AI-assisted customer support", "Continued website management and expansion"];

export default function NexDrainCaseStudy(){
  return <main><Navbar/>
    <section className="relative overflow-hidden bg-[#06172d] px-6 py-20 text-white md:py-28"><div className="hero-grid-dark absolute inset-0"/><div className="absolute -right-36 top-0 h-[560px] w-[560px] rounded-full bg-blue-500/20 blur-[120px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.88fr_1.12fr]"><div><p className="text-sm font-black uppercase tracking-[.24em] text-blue-300">Website case study</p><h1 className="mt-6 text-balance text-5xl font-black leading-[.98] tracking-[-.055em] md:text-7xl">NexDrain Plumbing</h1><p className="mt-7 text-xl leading-9 text-slate-300">A complete professional website designed around trust, local service visibility, real project proof, and easy customer action.</p><div className="mt-10 flex flex-col gap-4 sm:flex-row"><a href="https://nexdrainplumbing.net" target="_blank" rel="noreferrer" className="button-primary">Visit the Live Website<Icon name="arrow" className="h-5 w-5"/></a><Link href="/start-a-project" className="button-dark-outline">Start a Similar Project</Link></div></div><WebsiteShowcase compact/></div></section>
    <section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-[.22em] text-[#2563eb]">The challenge</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] md:text-5xl">Build a digital presence that matched the quality of the work.</h2><p className="mt-6 text-lg leading-8 text-[#607991]">NexDrain needed to replace an outdated website with a trustworthy local presence that clearly presented its plumbing services, service areas, reviews, project experience, and contact options.</p><p className="mt-5 text-lg leading-8 text-[#607991]">The website also needed a structure that could continue expanding as the business added service content, city pages, project photos, analytics, and customer-support tools.</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-[30px] border border-[#dce7f2] shadow-[0_24px_70px_rgba(23,62,103,.12)]"><Image src="/portfolio/nexdrain/trucks.jpg" alt="NexDrain Plumbing trucks" fill sizes="(max-width: 1024px) 100vw, 560px" className="object-cover"/></div></div></section>
    <section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-sm font-black uppercase tracking-[.22em] text-[#2563eb]">What AtlasBlake built</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] md:text-5xl">A complete customer-focused foundation.</h2><p className="mt-6 leading-7 text-[#607991]">Every part of the public experience was organized around the questions a homeowner asks: What do you do? Where do you work? Can I trust you? How quickly can I reach you?</p></div><div className="grid gap-4 sm:grid-cols-2">{built.map(item=><div key={item} className="flex gap-3 rounded-xl border border-[#dce7f2] bg-white p-5 font-extrabold text-[#405c77]"><Icon name="check" className="mt-0.5 h-5 w-5 shrink-0 text-[#2563eb]"/>{item}</div>)}</div></div></div></section>
    <section className="bg-white px-6 py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-6 md:grid-cols-2"><ProjectImage src="/portfolio/nexdrain/camera-inspection.jpg" alt="Plumbing camera inspection service photography" label="Real service photography"/><ProjectImage src="/portfolio/nexdrain/leak-detection.jpg" alt="Water leak detection service photography" label="Service-specific content"/></div><div className="mt-6 grid gap-6 md:grid-cols-2"><ProjectImage src="/portfolio/nexdrain/water-main-before.jpg" alt="Water main repair before" label="Before project proof"/><ProjectImage src="/portfolio/nexdrain/water-main-after.jpg" alt="Water main repair after" label="After project proof"/></div></div></section>
    <section className="bg-[#06172d] px-6 py-24 text-white"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-black uppercase tracking-[.22em] text-blue-300">The result</p><h2 className="mt-5 text-4xl font-black tracking-[-.04em] md:text-6xl">A professional online home built to keep growing.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-300"><p>The finished website gives NexDrain a complete professional presence, a scalable local SEO page structure, clearer service discovery, real project and customer proof, and faster paths to call or request service.</p><p>AtlasBlake does not claim unverified traffic or revenue increases. Performance can be measured over time through the analytics and Search Console foundation connected to the website.</p><p className="font-extrabold text-white">The strongest result is a website the company can confidently use, expand, and improve as the business grows.</p></div></div></section>
    <MarketingCta/><Footer/></main>;
}

function ProjectImage({src,alt,label}:{src:string;alt:string;label:string}){return <figure className="overflow-hidden rounded-[26px] border border-[#dce7f2] bg-white shadow-[0_18px_55px_rgba(23,62,103,.09)]"><div className="relative aspect-[16/10]"><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 560px" className="object-cover"/></div><figcaption className="px-6 py-4 text-sm font-black uppercase tracking-[.14em] text-[#1d5fd0]">{label}</figcaption></figure>}
