import type { Metadata } from "next";
import Footer from "../../components/Footer";
import { Icon } from "../../components/Icons";
import MarketingCta from "../../components/MarketingCta";
import Navbar from "../../components/Navbar";
import PageHero from "../../components/PageHero";
import { MaterioryVisual } from "../../components/ProjectVisuals";
import SectionHeading from "../../components/SectionHeading";

export const metadata: Metadata = { title: "Materiory Project", description: "A private inventory and project organization application for makers, crafters, and creative workspaces.", alternates: { canonical: "/work/materiory" } };
export default function MaterioryPage() { return <main><Navbar /><PageHero eyebrow="Inventory web application" title="A calmer way to organize creative inventory." text="Materiory is a private application designed to help makers keep track of materials, purchases, receipts, projects, and wish lists without turning the experience into a complicated warehouse system." primaryLabel="Discuss a Similar App" secondaryLabel="View All Work" secondaryHref="/work"/><section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-2"><div><SectionHeading eyebrow="The product" title="Simple for the user. Structured underneath." text="The experience is designed for everyday use by people who need organization without software getting in the way."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Inventory management","Purchase tracking","Receipt uploads","Wishlist organization","Duplicate detection","Project planning","Global search","Private PIN access"].map((item)=><div key={item} className="flex items-center gap-3 rounded-xl border border-[#dce7f2] bg-[#f9fbfd] px-4 py-3 font-bold text-[#405d78]"><Icon name="check" className="h-5 w-5 text-[#1265df]" />{item}</div>)}</div></div><MaterioryVisual /></div></section><section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">{[["01","Organize","Keep materials, quantities, locations, and purchase details in one place."],["02","Plan","Connect materials and ideas to current and future creative projects."],["03","Avoid duplicates","Search existing inventory before buying the same item again."]].map(([num,title,text])=><div key={num} className="rounded-2xl border border-[#dce7f2] bg-white p-7"><p className="text-xs font-black tracking-[.2em] text-[#1265df]">{num}</p><h2 className="mt-5 text-2xl font-extrabold">{title}</h2><p className="mt-4 leading-7 text-[#607991]">{text}</p></div>)}</div></section><MarketingCta title="Have an internal tool idea?" text="A focused private application can replace spreadsheets, scattered notes, and repetitive work without becoming a huge enterprise platform."/><Footer /></main>; }
