import type { Metadata } from "next";
import Footer from "../../components/Footer";
import { Icon } from "../../components/Icons";
import MarketingCta from "../../components/MarketingCta";
import Navbar from "../../components/Navbar";
import { OperationsVisual } from "../../components/ProjectVisuals";
import SectionHeading from "../../components/SectionHeading";

export const metadata: Metadata = { title: "BTC Fleet", description: "A connected fleet operations, driver workflow, digital eTicket, customer portal, and delivery documentation platform.", alternates: { canonical: "/products/btc-fleet" } };
export default function BtcFleetPage(){return <main><Navbar/><section className="relative overflow-hidden bg-[#06172d] px-6 py-24 text-white md:py-32"><div className="hero-grid-dark absolute inset-0"/><div className="absolute -right-32 top-0 h-[620px] w-[620px] rounded-full bg-blue-500/20 blur-[130px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.88fr_1.12fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.24em] text-blue-300">Flagship operational platform</p><h1 className="mt-6 text-6xl font-extrabold tracking-[-.06em] md:text-8xl">BTC Fleet</h1><p className="mt-6 text-xl leading-9 text-slate-300">Fleet operations, driver workflows, digital eTickets, customer access, and delivery documentation in one connected system built for ready-mix operations.</p><span className="mt-7 inline-flex rounded-full bg-white/10 px-4 py-2 text-xs font-extrabold text-blue-200">Private deployment</span></div><OperationsVisual/></div></section>
<section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Connected modules" title="The right experience for every part of the delivery workflow." text="BTC Fleet connects operational information while keeping each interface focused on what that user needs to do next."/><div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[["truck","Fleet operations","Track trucks, assignments, delivery movement, job activity, and operational status."],["phone","Driver application","Put load, job, ticket, water, signature, and delivery actions on a rugged field tablet."],["ticket","Digital eTickets","Create staged digital tickets that continue updating as operational data becomes available."],["portal","Customer access","Give customers secure job-level visibility into progress, tickets, and final documents."],["chart","Administration","Manage operations, users, records, archived tickets, customer access, and reports."],["link","System integrations","Connect dispatch, batch, GPS, and other operational data sources." ]].map(([icon,title,text])=><div key={title} className="marketing-card p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#eaf3ff] text-[#1265df]"><Icon name={icon as "truck"} className="h-6 w-6"/></span><h2 className="mt-6 text-2xl font-extrabold">{title}</h2><p className="mt-4 leading-7 text-[#607991]">{text}</p></div>)}</div></div></section>
<section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><SectionHeading eyebrow="Designed from the field" title="Operational details matter." text="Ready-mix delivery involves changing ticket data, plant-specific calculations, customer availability, signatures, quality-control records, and information arriving at different times. BTC Fleet was built around those realities."/><div className="rounded-[30px] bg-[#071a33] p-8 text-white md:p-10"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-blue-300">Platform principles</p><div className="mt-7 space-y-5">{["Show drivers the most important information as early as possible","Update ticket details in stages instead of waiting for every field","Keep customer access simple and job-specific","Generate dependable delivery and quality-control documentation","Support company and plant-specific operational rules"].map((item)=><div key={item} className="flex gap-3"><Icon name="check" className="mt-1 h-5 w-5 shrink-0 text-blue-300"/><p className="leading-7 text-slate-300">{item}</p></div>)}</div></div></div></section><MarketingCta eyebrow="Ready-mix technology" title="Interested in a platform built around your fleet?" text="BTC Fleet is currently a private deployment. AtlasBlake can discuss the workflow, integration requirements, and path for a company-specific implementation."/><Footer/></main>}
