import type { Metadata } from "next";
import Footer from "../../components/Footer";
import { Icon } from "../../components/Icons";
import MarketingCta from "../../components/MarketingCta";
import Navbar from "../../components/Navbar";
import PageHero from "../../components/PageHero";
import { WebsiteVisual } from "../../components/ProjectVisuals";
import SectionHeading from "../../components/SectionHeading";

export const metadata: Metadata = { title: "Business Website Design & Development", description: "Modern, mobile-first business websites with clear messaging, lead capture, SEO foundations, analytics, and cloud deployment.", alternates: { canonical: "/work/websites" } };
export default function WebsitesPage() { return <main><Navbar /><PageHero eyebrow="Website design & development" title="Websites built to earn trust and create action." text="A strong business website should explain what you do, make the next step obvious, work beautifully on every screen, and give your company a foundation that can evolve." primaryLabel="Start a Website Project" secondaryLabel="Website Services" secondaryHref="/services/website-development"/><section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-2"><WebsiteVisual/><div><SectionHeading eyebrow="What matters" title="More than a polished first impression." text="We combine visual design with practical content structure, responsive development, conversion paths, performance, and launch support."/><div className="mt-8 grid gap-4 sm:grid-cols-2">{["Clear positioning","Custom responsive design","Service and location pages","Quote and contact forms","SEO foundations","Analytics and tracking","Cloud deployment","Ongoing maintenance"].map((item)=><div key={item} className="flex items-center gap-3 rounded-xl border border-[#dce7f2] bg-[#f9fbfd] px-4 py-3 font-bold text-[#405d78]"><Icon name="check" className="h-5 w-5 text-[#1265df]" />{item}</div>)}</div></div></div></section><section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Built to expand" title="A website can be the front door to a larger digital system." text="Customer portals, quote workflows, scheduling, internal dashboards, and integrations can be added as the business and its digital needs grow."/><div className="mt-12 grid gap-5 md:grid-cols-4">{[["browser","Public website"],["portal","Customer portal"],["spark","Automated follow-up"],["link","Business integrations"]].map(([icon,title])=><div key={title} className="rounded-2xl border border-[#dce7f2] bg-white p-6"><Icon name={icon as "browser"} className="h-7 w-7 text-[#1265df]"/><h3 className="mt-5 text-xl font-extrabold">{title}</h3></div>)}</div></div></section><MarketingCta title="Ready for a website that represents the business you are building?"/><Footer /></main>; }
