import type { Metadata } from "next";
import Footer from "../../components/Footer";
import { Icon } from "../../components/Icons";
import MarketingCta from "../../components/MarketingCta";
import Navbar from "../../components/Navbar";
import PageHero from "../../components/PageHero";
import { MaterioryVisual } from "../../components/ProjectVisuals";
import SectionHeading from "../../components/SectionHeading";

export const metadata: Metadata = { title: "Materiory", description: "A private inventory and project organization application for makers, crafters, and creative workspaces.", alternates: { canonical: "/products/materiory" } };
export default function MaterioryProductPage(){return <main><Navbar/><PageHero eyebrow="AtlasBlake product · In development" title="Materiory" text="A private inventory and project organization application for makers, crafters, sewing rooms, laser workspaces, and creative studios." primaryLabel="Discuss a Similar Product" secondaryLabel="View Project" secondaryHref="/work/materiory"/><section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-2"><MaterioryVisual/><div><SectionHeading eyebrow="One organized workspace" title="Know what you have, where it is, and what it is for." text="Materiory brings materials, purchases, receipts, projects, and wish lists together in a simple private application."/><div className="mt-8 grid gap-4 sm:grid-cols-2">{["Materials and quantities","Storage locations","Purchase history","Receipt uploads","Project planning","Wishlist tracking","Duplicate detection","Global search"].map((item)=><div key={item} className="flex items-center gap-3 rounded-xl border border-[#dce7f2] bg-[#f9fbfd] px-4 py-3 font-bold text-[#405d78]"><Icon name="check" className="h-5 w-5 text-[#1265df]"/>{item}</div>)}</div></div></div></section><section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Product direction" title="Private, practical, and intentionally simple." text="Materiory is being designed for a small group of real users—not as a social network or an overloaded enterprise inventory platform."/><div className="mt-12 grid gap-6 md:grid-cols-3">{[["users","Easy to learn","A straightforward interface for users who want organization without complexity."],["shield","Private by default","Personal inventory and project information stays inside the user’s own workspace."],["layers","Ready to grow","Start with inventory and add useful workflows as real needs appear."]].map(([icon,title,text])=><div key={title} className="marketing-card p-7"><Icon name={icon as "users"} className="h-7 w-7 text-[#1265df]"/><h2 className="mt-5 text-2xl font-extrabold">{title}</h2><p className="mt-4 leading-7 text-[#607991]">{text}</p></div>)}</div></div></section><MarketingCta title="Have a product idea that starts with a real problem?"/><Footer/></main>}
