import type { Metadata } from "next";
import Link from "next/link";
import Footer from "../components/Footer";
import { Icon } from "../components/Icons";
import MarketingCta from "../components/MarketingCta";
import Navbar from "../components/Navbar";
import PageHero from "../components/PageHero";
import { MaterioryVisual, OperationsVisual } from "../components/ProjectVisuals";
import { products } from "../lib/marketing";

export const metadata: Metadata = { title: "Products", description: "Explore BTC Fleet, Materiory, and company-specific software built by AtlasBlake Technologies.", alternates: { canonical: "/products" } };
export default function ProductsPage() { return <main><Navbar /><PageHero eyebrow="AtlasBlake products" title="Focused products born from real workflows." text="Some business problems become reusable products. Others remain private, company-specific systems. AtlasBlake builds both." primaryLabel="Discuss a Custom System" secondaryLabel="View Our Work" secondaryHref="/work"/>
<section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto max-w-7xl space-y-16"><ProductCard product={products[0]} href="/products/btc-fleet" visual={<OperationsVisual/>} dark/><ProductCard product={products[1]} href="/products/materiory" visual={<MaterioryVisual/>} reverse/></div></section>
<section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.22em] text-[#1265df]">Private software</p><h2 className="mt-5 text-4xl font-extrabold leading-[1.08] tracking-[-.045em] md:text-6xl">Not every useful system needs to become a public product.</h2><p className="mt-6 text-lg leading-8 text-[#5d7790]">AtlasBlake also builds private software for a single company—designed around its users, data, rules, customers, and competitive advantage.</p><Link href="/services/custom-software" className="button-primary mt-9">Explore Custom Software<Icon name="arrow" className="h-5 w-5"/></Link></div><div className="grid gap-5 sm:grid-cols-2">{[["shield","Private by design","Company-specific access, users, workflows, and information."],["layers","Built in stages","Launch the highest-value workflow first and expand from there."],["link","Connected","Integrate with the systems and data the business already uses."],["chart","Operational value","Measure success by work completed—not by a long feature list."]].map(([icon,title,text])=><div key={title} className="rounded-2xl border border-[#dce7f2] bg-white p-6"><Icon name={icon as "shield"} className="h-7 w-7 text-[#1265df]"/><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-3 leading-7 text-[#607991]">{text}</p></div>)}</div></div></section><MarketingCta/><Footer/></main>; }
function ProductCard({product,href,visual,dark=false,reverse=false}:{product:(typeof products)[number];href:string;visual:React.ReactNode;dark?:boolean;reverse?:boolean}){return <article className={`grid items-center gap-12 rounded-[34px] p-7 md:p-12 lg:grid-cols-2 ${dark?"bg-[#06172d] text-white":"border border-[#dce7f2] bg-[#f9fbfd]"}`}><div className={reverse?"lg:order-2":""}><p className={`text-xs font-extrabold uppercase tracking-[.2em] ${dark?"text-blue-300":"text-[#1265df]"}`}>{product.label}</p><h2 className="mt-4 text-4xl font-extrabold tracking-[-.04em] md:text-6xl">{product.title}</h2><p className={`mt-5 text-lg leading-8 ${dark?"text-slate-300":"text-[#5e7891]"}`}>{product.description}</p><span className={`mt-6 inline-flex rounded-full px-4 py-2 text-xs font-extrabold ${dark?"bg-white/10 text-blue-200":"bg-[#eaf3ff] text-[#0b5cc8]"}`}>{product.status}</span><div><Link href={href} className={`mt-9 ${dark?"button-primary":"button-secondary"}`}>Explore Product<Icon name="arrow" className="h-5 w-5"/></Link></div></div><div className={reverse?"lg:order-1":""}>{visual}</div></article>}
