import type { Metadata } from "next";
import Link from "next/link";
import Footer from "../components/Footer";
import { Icon } from "../components/Icons";
import Navbar from "../components/Navbar";
import PageHero from "../components/PageHero";

export const metadata: Metadata = { title: "Support", description: "Support information for AtlasBlake Technologies websites, software, portals, applications, and connected systems.", alternates: { canonical: "/support" } };
export default function SupportPage(){return <main><Navbar/><PageHero eyebrow="Client support" title="Help for the systems your business relies on." text="Existing AtlasBlake clients can use the support email below for access questions, technical issues, change requests, and system assistance."/>
<section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-6 md:grid-cols-3">{[["mail","Contact support","Email support@atlasblaketech.com with the company name, affected system, and a clear description of the issue."],["clock","Include timing","Tell us when the issue began, whether it is still happening, and whether work is currently blocked."],["layers","Share useful details","Screenshots, affected page names, ticket numbers, user roles, and exact error messages help narrow the problem quickly."]].map(([icon,title,text])=><div key={title} className="marketing-card p-7"><Icon name={icon as "mail"} className="h-7 w-7 text-[#1265df]"/><h2 className="mt-5 text-2xl font-extrabold">{title}</h2><p className="mt-4 leading-7 text-[#607991]">{text}</p></div>)}</div><div className="mt-12 rounded-[30px] bg-[#06172d] p-8 text-white md:p-12"><div className="grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-blue-300">Existing client?</p><h2 className="mt-4 text-3xl font-extrabold md:text-4xl">Send the support details directly.</h2><p className="mt-4 max-w-3xl leading-7 text-slate-300">For security, do not include passwords, private API keys, access tokens, or full payment information in an email.</p></div><a href="mailto:support@atlasblaketech.com" className="button-primary">Email Support<Icon name="arrow" className="h-5 w-5"/></a></div></div><p className="mt-10 text-center text-sm text-[#6b8299]">Planning a new project instead? <Link className="font-extrabold text-[#1265df]" href="/contact">Start a project inquiry.</Link></p></div></section><Footer/></main>}
