import type { Metadata } from "next";
import Link from "next/link";
import Footer from "../../components/Footer";
import { Icon } from "../../components/Icons";
import MarketingCta from "../../components/MarketingCta";
import Navbar from "../../components/Navbar";
import { OperationsVisual } from "../../components/ProjectVisuals";
import SectionHeading from "../../components/SectionHeading";

export const metadata: Metadata = { title: "Big Town Concrete Case Study", description: "A connected fleet, driver, digital eTicket, customer portal, and administrative platform built for Big Town Concrete.", alternates: { canonical: "/work/big-town-concrete" } };

export default function BigTownConcretePage() {
  return <main><Navbar />
    <section className="relative overflow-hidden bg-[#06172d] px-6 py-24 text-white md:py-32"><div className="hero-grid-dark absolute inset-0"/><div className="absolute -right-32 top-0 h-[620px] w-[620px] rounded-full bg-blue-500/20 blur-[130px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm font-extrabold uppercase tracking-[.24em] text-blue-300">Case study · Custom operations platform</p><h1 className="mt-6 text-balance text-5xl font-extrabold leading-[1.01] tracking-[-.055em] md:text-7xl">Turning a complex delivery workflow into one connected digital system.</h1><p className="mt-7 text-lg leading-8 text-slate-300">AtlasBlake designed and developed a custom platform spanning driver tablets, digital eTickets, customer access, reporting, and internal management for Big Town Concrete.</p><div className="mt-9 flex flex-wrap gap-3"><Tag text="Production system"/><Tag text="Driver application"/><Tag text="Customer portal"/><Tag text="Operational integrations"/></div></div><OperationsVisual /></div></section>
    <section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="The challenge" title="Critical information lived across disconnected workflows." text="Concrete delivery involves dispatch data, drivers, plant-specific calculations, ticket records, customer signatures, and final documentation. The system had to bring those parts together without slowing down the people doing the work."/><div className="grid gap-5 sm:grid-cols-2">{["Information arriving from multiple operational systems","Paper-dependent delivery and ticket workflows","Drivers needing immediate load and job details","Customers needing access to delivery documentation","Staff manually collecting and preparing records","Business rules that vary by plant and workflow stage"].map((item,index)=><div key={item} className="rounded-2xl border border-[#dce7f2] bg-[#f9fbfd] p-6"><p className="text-xs font-black tracking-[.2em] text-[#1265df]">0{index+1}</p><p className="mt-4 font-extrabold leading-7 text-[#29455f]">{item}</p></div>)}</div></div></section>
    <section className="border-y border-[#dce7f2] bg-[#f6f9fd] px-6 py-24 md:py-32"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="The solution" title="Six connected parts. One operational workflow." text="The platform gives each user a focused experience while keeping delivery information and documentation connected behind the scenes."/><div className="mt-16 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[
      ["phone","Driver tablet app","Load details, ordered slump, job information, water entry, signatures, and delivery actions designed for the truck."],
      ["ticket","Digital eTickets","A staged digital ticket that begins with the information drivers need and continues updating as delivery data becomes available."],
      ["chart","Administrative dashboard","Central access to active operations, tickets, archived records, customer access, and system management."],
      ["portal","Customer portal","Secure job-level access to progress, delivered quantity, tickets, supporting documents, and combined final PDFs."],
      ["link","Operational integrations","Connections to dispatch, batch, and fleet data sources so information can move into the platform automatically."],
      ["layers","PDF & QC documentation","Automated ticket, signature, acceptance, quality-control, and combined job documentation."],
    ].map(([icon,title,text])=><div key={title} className="marketing-card p-7"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#eaf3ff] text-[#1265df]"><Icon name={icon as "phone"} className="h-6 w-6" /></span><h3 className="mt-6 text-2xl font-extrabold">{title}</h3><p className="mt-4 leading-7 text-[#607991]">{text}</p></div>)}</div></div></section>
    <section className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-2"><div><SectionHeading eyebrow="Technical foundation" title="Built as a real operational system—not a presentation mockup." text="The platform combines cloud services, mobile interfaces, secure access, scheduled synchronization, PDF generation, and company-specific workflow logic."/><div className="mt-9 flex flex-wrap gap-3">{["Cloud-hosted frontend & backend","Role-based interfaces","Third-party data integrations","Automated ticket synchronization","Mobile app release management","Company-specific business rules"].map((item)=><span key={item} className="rounded-full border border-[#cfddea] bg-[#f8fbfe] px-4 py-2 text-sm font-bold text-[#405d78]">{item}</span>)}</div></div><div className="rounded-[30px] bg-[#071a33] p-7 text-white shadow-2xl md:p-10"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-blue-300">Result</p><h3 className="mt-5 text-3xl font-extrabold tracking-[-.035em]">One connected home for delivery information.</h3><div className="mt-8 space-y-5">{["Faster access to delivery and load information","Reduced dependence on paper documents","Customer self-service access to job records","Centralized ticket and document history","A platform designed to expand with operations"].map((item)=><div key={item} className="flex gap-3"><span className="mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-lg bg-blue-500/20 text-blue-300"><Icon name="check" className="h-4 w-4" /></span><p className="leading-7 text-slate-300">{item}</p></div>)}</div><Link href="/products/btc-fleet" className="button-primary mt-9">Explore BTC Fleet<Icon name="arrow" className="h-5 w-5" /></Link></div></div></section>
    <MarketingCta title="Need a system built around your operation?" text="AtlasBlake can help map the workflow, define the first useful release, and build a practical path from the current process to a connected platform."/><Footer /></main>;
}
function Tag({text}:{text:string}) { return <span className="rounded-full border border-white/15 bg-white/[.06] px-4 py-2 text-xs font-extrabold text-blue-100">{text}</span>; }
